version: "3.4"

services:
  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432
      POSTGRES_PASSWORD: postgres
  redis:
    image: redis:7
    ports:
      - 6379:6379
    environment:
      REDIS_URL: redis://redis:6379/0